version: '3'

services:
  database:
    image: mongo:5.0.0
    restart: unless-stopped
    # ports:
    #   - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=quang
      - MONGO_INITDB_ROOT_PASSWORD=Quang.0512
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    networks:
      - db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 5000:5000
    environment:
      - MONGO_USERNAME=quang
      - MONGO_PASSWORD=Quang.0512
      - MONGO_PORT=27017
      - MONGO_HOST=database
    networks:
      - app
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - 3210:80
    networks:
      - app

# volumes:

networks:
  app:
    driver: bridge
  db:
    driver: bridge
